### ISSUE TITLE
Missing required ENVs and files

### ISSUE THREAD

**Issue by stahh** [Senzing/senzingapi-runtime#10]
Hello. I just tested image with some services. And I think you need to add ENVs     and  COPY                                                       
```
 ENV SENZING_ROOT /opt/senzing/g2
ENV PYTHONPATH $SENZING_ROOT/python/senzing:$SENZING_ROOT/python
ENV LD_LIBRARY_PATH $SENZING_ROOT/lib:$SENZING_ROOT/lib/jre/lib/server:$SENZING_ROOT/lib/debian:$LD_LIBRARY_PATH
ENV CLASSPATH $SENZING_ROOT/lib/g2rst.jar:$SENZING_ROOT/lib/g2.jar:$CLASSPATH                                                  
    RUN mkdir -p /etc/opt/senzing
RUN cp -R /opt/senzing/g2/resources/templates/* /etc/opt/senzing/
```

**Comment by docktermj** [comment]
Hi @stahh !

The `senzing/senzingapi-runtime` image includes only those environment variables needed by the Senzing engine itself.   For Python and Java applications, the containers based off of the `senzing/senzingapi-runtime` will need to include appropriate environment variables for their specific application.

An example:   In a customer-built application container inheriting from `senzing/senzingapi-runtime` and using Python, you wouldn't expect to see a CLASSPATH environment variable, nor Java references in the LD_LIBRARY_PATH. We don't users of `senzing/senzingapi-runtime` to inherit inappropriate environment variables.

**Comment by docktermj** [comment]
Hello again, @stahh !

If those environment values are important to you across multiple images,  you may consider writing your own "base" Dockerfile that includes the tailored environment variables.   Then in the `FROM` of your multiple images, use your "base" container.

**Comment by docktermj** [comment]
@stahh 

On the lines concerning `/etc/opt/senzing` ...

When running the container, there are 6 files in `/etc/opt/senzing`.  Are you expecting others?

Example:

```console
$ docker run -it senzing/senzingapi-runtime:0.1.0 /bin/bash

root@04a416568c25:/# cd /etc/opt/senzing/
root@04a416568c25:/etc/opt/senzing# ls
cfgVariant.json  customOn.txt  defaultGNRCP.config
customGn.txt	 customSn.txt  stb.config
```

**Comment by docktermj** [comment]
@stahh Thank you for engaging us on this!  As you can see by version `0.1.0` we are in the early alpha/beta stages of this container.  We are eager to know if we've missed anything.
