### ISSUE TITLE
Incorporate senzingapi-runtime package

### ISSUE THREAD

**Issue by roncewind** [Senzing/senzingapi-runtime#6]
see https://github.com/Senzing/community-roadmap/issues/65

**Comment by roncewind** [comment]
We're as far as we can go until more testing is done and we can create a "real" release of this Docker image.

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/senzingapi-runtime/pull/7
- https://github.com/Senzing/senzingapi-runtime/pull/8
- https://github.com/Senzing/senzingapi-runtime/pull/9
- https://github.com/Senzing/senzingapi-runtime/pull/11
